(()=>{'use strict';const c=window.HAYATI_CONFIG||{};const sb=(window.supabase&&c.SUPABASE_URL&&c.SUPABASE_ANON_KEY)?window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_ANON_KEY):null;const $=s=>document.querySelector(s);const loginView=$('#loginView'),adminView=$('#adminView');
function msg(el,text){$(el).textContent=text||''}function money(n){return new Intl.NumberFormat('ar-DZ').format(Number(n)||0)+' دج'}
$('#togglePass').onclick=()=>{const i=$('#password');i.type=i.type==='password'?'text':'password'};
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!sb){msg('#loginMsg','إعدادات Supabase غير موجودة.');return}msg('#loginMsg','جاري تسجيل الدخول...');const {error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error){msg('#loginMsg','بيانات الدخول غير صحيحة.');return}showAdmin();loadOrders();loadProducts()};
$('#logout').onclick=async()=>{await sb?.auth.signOut();adminView.classList.add('hidden');loginView.classList.remove('hidden')};
function showAdmin(){loginView.classList.add('hidden');adminView.classList.remove('hidden')}
async function init(){if(!sb){msg('#loginMsg','إعدادات Supabase غير موجودة.');return}const {data}=await sb.auth.getSession();if(data.session){showAdmin();loadOrders();loadProducts()}}
async function loadOrders(){msg('#ordersMsg','جاري تحميل الطلبات...');const {data,error}=await sb.from('orders').select('*').order('created_at',{ascending:false});if(error){msg('#ordersMsg','تعذر تحميل الطلبات: '+error.message);$('#ordersBody').innerHTML='';return}msg('#ordersMsg','');$('#ordersBody').innerHTML=(data||[]).map(o=>{const items=Array.isArray(o.items)?o.items.map(x=>`${x.name||'منتج'} × ${x.qty||1}`).join('، '):String(o.items||'');const address=o.pickup_point||o.address||o.customer_address||'';return `<tr><td>${o.created_at?new Date(o.created_at).toLocaleString('ar-DZ'):''}</td><td>${esc(o.customer_name)}</td><td>${esc(o.phone)}</td><td>${esc(o.wilaya)}</td><td>${esc(o.municipality)}</td><td>${esc(address)}</td><td>${money(o.total)}</td><td>${esc(items)}</td></tr>`}).join('')||'<tr><td colspan="8">لا توجد طلبات.</td></tr>'}
async function loadProducts(){msg('#productsMsg','جاري تحميل المنتجات...');const {data,error}=await sb.from('products').select('*');if(error){msg('#productsMsg','تعذر تحميل المنتجات: '+error.message);return}msg('#productsMsg','');$('#productGrid').innerHTML=(data||[]).map(p=>`<article class="product-card"><img src="${esc(p.image_url||p.image||'')}" onerror="this.style.visibility='hidden'"><div class="pc"><h3>${esc(p.name||p.title||'منتج')}</h3><p>${esc(p.category||'')}</p><b>${money(p.price)}</b><div class="actions"><button class="ghost" data-edit="${esc(p.id)}">تعديل</button><button class="ghost" data-del="${esc(p.id)}">حذف</button></div></div></article>`).join('')||'<p>لا توجد منتجات.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProduct((data||[]).find(p=>String(p.id)===String(b.dataset.edit))));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.del))}
function openProduct(p){$('#productModal').classList.remove('hidden');$('#productTitle').textContent=p?'تعديل منتج':'إضافة منتج';$('#productId').value=p?.id||'';$('#pName').value=p?.name||p?.title||'';$('#pCategory').value=p?.category||'';$('#pPrice').value=p?.price??'';$('#pImage').value=p?.image_url||p?.image||'';msg('#productFormMsg','')}
function closeProduct(){$('#productModal').classList.add('hidden')}$('#newProduct').onclick=()=>openProduct(null);$('#closeProduct').onclick=closeProduct;$('#cancelProduct').onclick=closeProduct;
$('#productForm').onsubmit=async e=>{e.preventDefault();msg('#productFormMsg','جاري الحفظ...');const id=$('#productId').value;const row={name:$('#pName').value.trim(),category:$('#pCategory').value,price:Number($('#pPrice').value)||0,image_url:$('#pImage').value.trim()||null};let r=id?await sb.from('products').update(row).eq('id',id):await sb.from('products').insert(row);if(r.error){msg('#productFormMsg','تعذر الحفظ: '+r.error.message);return}closeProduct();loadProducts()};
async function deleteProduct(id){if(!confirm('هل تريدين حذف هذا المنتج؟'))return;const {error}=await sb.from('products').delete().eq('id',id);if(error){msg('#productsMsg','تعذر الحذف: '+error.message);return}loadProducts()}
$('#refreshOrders').onclick=loadOrders;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));$('#'+b.dataset.tab).classList.remove('hidden')});$('#productModal').onclick=e=>{if(e.target.id==='productModal')closeProduct()};function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}init()})();
