(()=>{'use strict';
const demo=[
{id:'demo-1',name:'فستان وردي ناعم',category:'ملابس',price:2900,image:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=700&q=80'},
{id:'demo-2',name:'بلوزة أنيقة',category:'ملابس',price:1850,image:'https://images.unsplash.com/photo-1564257577054-0e5ab90e0f0f?auto=format&fit=crop&w=700&q=80'},
{id:'demo-3',name:'عباية مطرزة',category:'ملابس',price:3500,image:'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=700&q=80'},
{id:'demo-4',name:'عطر نسائي أنيق',category:'عطور',price:2200,image:'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=700&q=80'},
{id:'demo-5',name:'سيروم للبشرة',category:'مواد التجميل',price:1950,image:'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=700&q=80'},
{id:'demo-6',name:'أحمر شفاه مطفي',category:'مواد التجميل',price:1250,image:'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=700&q=80'},
{id:'demo-7',name:'حذاء نسائي أنيق',category:'أحذية',price:3200,image:'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=700&q=80'},
{id:'demo-8',name:'حذاء بكعب أنيق',category:'أحذية',price:3900,image:'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=700&q=80'}];
const wilayas=['أدرار','الشلف','الأغواط','أم البواقي','باتنة','بجاية','بسكرة','بشار','البليدة','البويرة','تمنراست','تبسة','تلمسان','تيارت','تيزي وزو','الجزائر','الجلفة','جيجل','سطيف','سعيدة','سكيكدة','سيدي بلعباس','عنابة','قالمة','قسنطينة','المدية','مستغانم','المسيلة','معسكر','ورقلة','وهران','البيض','إليزي','برج بوعريريج','بومرداس','الطارف','تندوف','تيسمسيلت','الوادي','خنشلة','سوق أهراس','تيبازة','ميلة','عين الدفلى','النعامة','عين تموشنت','غرداية','غليزان','تيميمون','برج باجي مختار','أولاد جلال','بني عباس','عين صالح','عين قزام','تقرت','جانت','المغير','المنيعة'];
const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('ar-DZ').format(Number(n)||0)+' دج',esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let products=[...demo],cart=loadCart(),activeCat='',toastTimer;function loadCart(){try{const x=JSON.parse(localStorage.getItem('hayati_cart')||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function save(){localStorage.setItem('hayati_cart',JSON.stringify(cart));renderCart()}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2300)}
function renderProducts(){const q=($('#search').value||'').trim().toLowerCase();const list=products.filter(p=>(!activeCat||p.category===activeCat)&&(!q||String(p.name||'').toLowerCase().includes(q)||String(p.category||'').toLowerCase().includes(q)));$('#list').innerHTML=list.length?list.map(p=>`<article class="product"><div class="pic"><img src="${esc(p.image||'')}" alt="${esc(p.name)}" style="width:100%;height:100%;object-fit:cover" onerror="this.style.display='none';this.parentElement.textContent='🛍️'"></div><div class="info"><h3>${esc(p.name)}</h3><span>${esc(p.category)}</span><p class="price">${money(p.price)}</p><button class="buy" data-id="${esc(p.id)}">أضيفي إلى السلة</button></div></article>`).join(''):'<div class="status">لا توجد منتجات حاليا.</div>';document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>add(b.dataset.id))}
function renderCart(){const qty=cart.reduce((s,x)=>s+(Number(x.qty)||0),0);$('#cartCount').textContent=qty;const total=cart.reduce((s,x)=>s+(Number(x.price)||0)*(Number(x.qty)||0),0);$('#cartItems').innerHTML=cart.length?cart.map(x=>`<div class="row"><span>${esc(x.name)}<br><small>${money(x.price)} × ${x.qty}</small></span><span><button data-minus="${esc(x.id)}">−</button> ${x.qty} <button data-plus="${esc(x.id)}">+</button> <button class="remove" data-remove="${esc(x.id)}">حذف</button></span></div>`).join(''):'<p class="status">السلة فارغة.</p>';$('#total').textContent=new Intl.NumberFormat('ar-DZ').format(total);document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>change(b.dataset.minus,-1));document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>change(b.dataset.plus,1));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>String(x.id)!==String(b.dataset.remove));save()})}
function add(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;const x=cart.find(x=>String(x.id)===String(id));x?x.qty++:cart.push({id:p.id,name:p.name,price:Number(p.price)||0,qty:1});save();toast('تمت إضافة طلبك إلى السلة ✓')}
function change(id,d){const x=cart.find(x=>String(x.id)===String(id));if(!x)return;x.qty=(Number(x.qty)||0)+d;if(x.qty<1)cart=cart.filter(y=>String(y.id)!==String(id));save()}
function open(m){m.style.display='flex';m.setAttribute('aria-hidden','false')}function close(m){m.style.display='none';m.setAttribute('aria-hidden','true')}
async function connect(){const c=window.HAYATI_CONFIG||{};if(!c.SUPABASE_URL||!c.SUPABASE_ANON_KEY||!window.supabase)return;try{const sb=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_ANON_KEY);window.HAYATI_DB=sb;let r=await sb.from('products').select('*');if(r.error){console.warn(r.error);return}if(Array.isArray(r.data)&&r.data.length){products=r.data.map(p=>({id:p.id,name:p.name||p.title||'منتج',category:p.category||'',price:Number(p.price)||0,image:p.image_url||p.image||''}))}}catch(e){console.warn(e)}}
$('#wilaya').innerHTML='<option value="">اختاري الولاية</option>'+wilayas.map(w=>`<option value="${esc(w)}">${esc(w)}</option>`).join('');
document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{activeCat=activeCat===b.dataset.cat?'':b.dataset.cat;document.querySelectorAll('.cat').forEach(x=>x.classList.toggle('active',x===b&&!!activeCat));renderProducts();document.querySelector('#products').scrollIntoView({behavior:'smooth'})});
$('#search').oninput=renderProducts;$('#cartBtn').onclick=()=>open($('#cartModal'));$('#closeCart').onclick=()=>close($('#cartModal'));$('#closeCheckout').onclick=()=>close($('#checkoutModal'));$('#checkoutBtn').onclick=()=>{if(!cart.length){toast('السلة فارغة، أضيفي منتجا أولا');return}close($('#cartModal'));open($('#checkoutModal'));$('#orderMsg').textContent=''};
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)close(m)}));
$('#orderForm').onsubmit=async e=>{e.preventDefault();const msg=$('#orderMsg');msg.textContent='جاري إرسال الطلب...';const f=new FormData(e.target),total=cart.reduce((s,x)=>s+x.price*x.qty,0);const customer_name=String(f.get('customer_name')||'').trim(),phone=String(f.get('phone')||'').trim(),wilaya=String(f.get('wilaya')||''),municipality=String(f.get('municipality')||'').trim(),pickup=String(f.get('pickup_point')||'').trim();if(!customer_name||!phone||!wilaya||!municipality||!pickup){msg.textContent='يرجى ملء جميع الخانات المطلوبة.';return}const base={customer_name,phone,wilaya,municipality,items:cart,total};try{if(!window.HAYATI_DB)throw new Error('Supabase غير متصل');const variants=[{...base,pickup_point:pickup},{...base,address:pickup},{...base,pickup_point:pickup,customer_address:pickup},{...base,address:pickup,customer_address:pickup}];let last=null,success=false;for(const payload of variants){const r=await window.HAYATI_DB.from('orders').insert(payload);if(!r.error){success=true;break}last=r.error;const text=String(r.error.message||'').toLowerCase();if(!/column|schema cache|does not exist|could not find|unknown/i.test(text))break}if(!success)throw last||new Error('تعذر حفظ الطلب');cart=[];save();e.target.reset();msg.textContent='تم تأكيد طلبك بنجاح ✓';toast('تم تأكيد طلبك بنجاح ✓')}catch(err){console.error(err);const detail=String(err?.message||'');msg.textContent=detail&&/row-level|permission|policy|rls/i.test(detail)?'الطلب جاهز، لكن صلاحية إضافة الطلبات في Supabase تحتاج إلى تفعيل.':'تعذر إرسال الطلب إلى قاعدة البيانات. راجعي إعداد جدول orders.'}};
renderCart();renderProducts();connect().then(renderProducts);
})();
